name: afl

on:
  push:
    branches:
      - afl
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: afl
      bin: cargo-afl
    permissions:
      contents: write
    secrets: inherit
