name: buck2

on:
  push:
    branches:
      - buck2
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: buck2
      git: facebookincubator/buck2
      path: cli
    permissions:
      contents: write
    secrets: inherit
