name: buck2

on:
  push:
    branches:
      - buck2

jobs:
  build:
    uses: ./build.yml
    with:
      crate: buck2
      git: facebookincubator/buck2
      path: cli
    permissions:
      contents: write
    secrets: inherit
