name: cargo-web

on:
  push:
    branches:
      - cargo-web

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-web
    permissions:
      contents: write
    secrets: inherit
