name: cargo-outdated

on:
  push:
    branches:
      - cargo-outdated

jobs:
  build:
    uses: ./build.yml
    with:
      crate: cargo-outdated
    permissions:
      contents: write
    secrets: inherit
