name: cargo-fuzz

on:
  push:
    branches:
      - cargo-fuzz

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-fuzz
    permissions:
      contents: write
    secrets: inherit
