name: cargo-tally

on:
  push:
    branches:
      - cargo-tally

jobs:
  build:
    uses: dtolnay/install/.github/workflows/build.yml@master
    with:
      crate: cargo-tally
    permissions:
      contents: write
    secrets: inherit
