name: cargo-expand

on:
  push:
    branches:
      - cargo-expand

jobs:
  build:
    uses: ./build.yml
    with:
      crate: cargo-expand
    permissions:
      contents: write
    secrets: inherit
