name: cargo-outdated

on:
  push:
    branches:
      - cargo-outdated

jobs:
  build:
    uses: dtolnay/install/.github/workflows/build.yml@master
    with:
      crate: cargo-outdated
    permissions:
      contents: write
    secrets: inherit
