name: cargo-rm

on:
  push:
    branches:
      - cargo-rm

jobs:
  build:
    uses: dtolnay/install/.github/workflows/build.yml@master
    with:
      crate: cargo-rm
    secrets:
      private_key: ${{secrets.private_key}}
