name: cargo-set-version

on:
  push:
    branches:
      - cargo-set-version
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-edit
      bin: cargo-set-version
    permissions:
      contents: write
    secrets: inherit
