name: cargo-expand

on:
  push:
    tags:
      - cargo-expand

jobs:
  build:
    uses: dtolnay/install/.github/workflows/build.yml@master
    with:
      crate: cargo-expand
      private_key: ${{secrets.private_key}}
