name: cargo-llvm-lines

on:
  push:
    branches:
      - cargo-llvm-lines

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cargo-llvm-lines
    permissions:
      contents: write
    secrets: inherit
