name: cbindgen

on:
  push:
    branches:
      - cbindgen

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cbindgen
    permissions:
      contents: write
    secrets: inherit
