name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule: [cron: "40 1 * * *"]

permissions:
  contents: read

jobs:
  install:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          crate: cargo-outdated
      - run: cargo outdated --version
