name: cxxbridge-cmd

on:
  push:
    tags:
      - cxxbridge-cmd

jobs:
  build:
    uses: dtolnay/install/.github/workflows/build.yml@master
    with:
      crate: cxxbridge-cmd
      bin: cxxbridge
      private_key: ${{secrets.private_key}}
