name: cxxbridge-cmd

on:
  push:
    branches:
      - cxxbridge-cmd

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: cxxbridge-cmd
      bin: cxxbridge
    permissions:
      contents: write
    secrets: inherit
