name: cxxbridge-cmd

on:
  push:
    tags:
      - cxxbridge-cmd

jobs:
  build:
    name: cxxbridge-cmd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cxxbridge-cmd
      - id: which
        run: echo "::set-output name=which::$(which cxxbridge)"
      - run: echo "$PRIVATE_KEY" | gpg --import
        env:
          PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}
      - run: gpg --output cxxbridge.sig --detach-sig ${{steps.which.outputs.which}}
      - run: gpg --output signing-key.gpg --dearmor signing-key.asc
      - run: gpg --no-default-keyring --keyring ./signing-key.gpg --verify cxxbridge.sig ${{steps.which.outputs.which}}
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{steps.which.outputs.which}}
            cxxbridge.sig
          fail_on_unmatched_files: true
