name: dircnt

on:
  push:
    branches:
      - dircnt

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: dircnt
    permissions:
      contents: write
    secrets: inherit
