name: faketty

on:
  push:
    branches:
      - faketty

jobs:
  build:
    uses: dtolnay/install/.github/workflows/build.yml@master
    with:
      crate: faketty
    permissions:
      contents: write
    secrets:
      private_key: ${{secrets.private_key}}
