name: faketty

on:
  push:
    branches:
      - faketty

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: faketty
    permissions:
      contents: write
    secrets: inherit
