name: honggfuzz

on:
  push:
    branches:
      - honggfuzz
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: honggfuzz
      bin: cargo-hfuzz
    permissions:
      contents: write
    secrets: inherit
