name: reindeer

on:
  push:
    branches:
      - reindeer

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: reindeer
      git: facebookincubator/reindeer
    permissions:
      contents: write
    secrets: inherit
