name: rustup-toolchain-install-master

on:
  push:
    branches:
      - rustup-toolchain-install-master

jobs:
  build:
    uses: dtolnay/install/.github/workflows/build.yml@master
    with:
      crate: rustup-toolchain-install-master
    permissions:
      contents: write
    secrets:
      private_key: ${{secrets.private_key}}
