name: rustup-toolchain-install-master

on:
  push:
    branches:
      - rustup-toolchain-install-master

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: rustup-toolchain-install-master
      git: https://github.com/dtolnay-contrib/rustup-toolchain-install-master
      branch: nodefault
    permissions:
      contents: write
    secrets: inherit
