name: sha1dir

on:
  push:
    branches:
      - sha1dir

jobs:
  build:
    uses: dtolnay/install/.github/workflows/build.yml@master
    with:
      crate: sha1dir
    permissions:
      contents: write
    secrets:
      private_key: ${{secrets.private_key}}
