name: star-history

on:
  push:
    branches:
      - star-history

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: star-history
    permissions:
      contents: write
    secrets: inherit
