name: xargo

on:
  push:
    branches:
      - xargo

jobs:
  build:
    uses: dtolnay/install/.github/workflows/build.yml@master
    with:
      crate: xargo
    permissions:
      contents: write
    secrets: inherit
