name: xargo

on:
  push:
    branches:
      - xargo
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      crate: xargo
    permissions:
      contents: write
    secrets: inherit
